### PR TITLE
Fix for REST bugs and certain metrics in bench

### PR DESCRIPTION
**Pull request by lucyge2022**
small fixes for REST bugs and certain metrics in bench

### CODE REVIEW

**Comment by LuQQiu** [comment]
@lucyge2022 Please help fix the test failure

**Comment by LuQQiu** [comment]
the test runs pre-commit fmt and check which needs to be installed locally

**Comment by LuQQiu** [comment]
@lucyge2022 i plan to do non-trivial changes to the perf bench, fyi, if we concurrently modify it, may not compile lol

**Comment by lucyge2022** [comment]
> @lucyge2022 i plan to do non-trivial changes to the perf bench, fyi, if we concurrently modify it, may not compile lol

please go ahead.

**Pull request merged**
