### PR TITLE
Fix the bug after introducing ufs full path as page id

### PR DESCRIPTION
**Pull request by YichuanSun**
In Alluxio 3.3, we use the ufs full path as the fileId, instead of a hash String. It breaks the fsspec/alluxiofs, this PR is used to fix the bugs.

### CODE REVIEW

**Comment by YichuanSun** [comment]
I have run the fixed alluxiofs with the Alluxio 3.3 locally, it passed the `test_read_range.py`. @LuQQiu could you please take a look?

**Comment by LuQQiu** [comment]
@SibylYang please help review and see whether that will break backward compatibility? e.g. whether it can still work with AOS

**Comment by SibylYang** [comment]
I tested it with alluxio open source cluster running locally. There's no problem with reading files. But there's an error when writing to files. Below code generate the error "io.UnsupportedOperation: not writable". 

`fsspec.register_implementation("alluxiofs", AlluxioFileSystem, clobber=True)
alluxio_fs = fsspec.filesystem("alluxiofs", etcd_hosts="localhost", etcd_port=2379, target_protocol='s3')

with alluxio_fs.open('s3://path/to/file', 'a') as f:
    f.write("\n111 new line by alluxio\n")
`

**Comment by YichuanSun** [comment]
After using the code in https://github.com/fsspec/alluxiofs/pull/51 and my change in current PR, I test the write function manually with the latest alluxio os edition, I find the write works. Here is my test script, the same as yours above.

```python
import sys
import fsspec
sys.path.append('.')
from alluxiofs import AlluxioClient, AlluxioFileSystem

if __name__ == "__main__":
    fsspec.register_implementation("alluxiofs", AlluxioFileSystem, clobber=True)
    alluxio_fs = fsspec.filesystem("alluxiofs", etcd_hosts="localhost", etcd_port=2379, target_protocol='s3')
    with alluxio_fs.open("s3://yichuan-test/testBucket/test.txt", 'a') as f:
        f.write("\n444 new line by alluxio\n")
```

After running the script and open the "s3://yichuan-test/testBucket/test.txt" in the S3 website, the content is as below.
```
Wow

 new line by alluxio

 new line by alluxio

 new line by alluxio

111 new line by alluxio

222 new line by alluxio

333 new line by alluxio

444 new line by alluxio
```

Are there probably no bugs? Just any wrong configurations or inherent bugs in our alluxiofs codebase? FYI @LuQQiu @SibylYang

**Comment by SibylYang** [comment]
> After using the code in #51 and my change in current PR, I test the write function manually with the latest alluxio os edition, I find the write works. Here is my test script, the same as yours above.
> 
> ```python
> import sys
> import fsspec
> sys.path.append('.')
> from alluxiofs import AlluxioClient, AlluxioFileSystem
> 
> if __name__ == "__main__":
>     fsspec.register_implementation("alluxiofs", AlluxioFileSystem, clobber=True)
>     alluxio_fs = fsspec.filesystem("alluxiofs", etcd_hosts="localhost", etcd_port=2379, target_protocol='s3')
>     with alluxio_fs.open("s3://yichuan-test/testBucket/test.txt", 'a') as f:
>         f.write("\n444 new line by alluxio\n")
> ```
> 
> After running the script and open the "s3://yichuan-test/testBucket/test.txt" in the S3 website, the content is as below.
> 
> ```
> Wow
> 
>  new line by alluxio
> 
>  new line by alluxio
> 
>  new line by alluxio
> 
> 111 new line by alluxio
> 
> 222 new line by alluxio
> 
> 333 new line by alluxio
> 
> 444 new line by alluxio
> ```
> 
> Maybe just any wrong configurations that cause the write error? FYI @LuQQiu @SibylYang

Right. If I used PR 51 --- the updated handler, then there's no problem with writing

**Comment by LuQQiu** [comment]
@SibylYang Please help review the PR

**Comment by SibylYang** [comment]
This commit LGTM. 
It won't break the alluxio open source, because in our alluxio java server, it process URL using something like 
`httpRequestUri.getParameters().get("offset")`
So the added "ufsFullPath" in the URL will just be ignored by alluxio open source.

**Review by LuQQiu — APPROVED** [review]
LGTM

**Pull request merged**
